.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. schezuancoin_qt test_schezuancoin_qt
clean: FORCE
	$(MAKE) -C .. schezuancoin_qt_clean test_schezuancoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_schezuancoin_qt_check
schezuancoin-qt schezuancoin-qt.exe: FORCE
	 $(MAKE) -C .. schezuancoin_qt
